name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}
          VERSION_TAG: ${{ github.ref_name }}
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION_TAG .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION_TAG